# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 9) do

  create_table "courses", :force => true do |t|
    t.column "code",       :string,  :default => "", :null => false
    t.column "bunban",     :string,  :default => "", :null => false
    t.column "title",      :string,  :default => "", :null => false
    t.column "credit",     :string,  :default => "", :null => false
    t.column "day_time",   :string
    t.column "prof",       :string
    t.column "num_of_std", :integer
    t.column "english",    :string
    t.column "abeek",      :string
    t.column "notice",     :string
    t.column "comment",    :string
    t.column "year",       :integer,                 :null => false
    t.column "semester",   :string,  :default => "", :null => false
    t.column "dept",       :string,  :default => "", :null => false
  end

  create_table "emails", :force => true do |t|
    t.column "address",    :string
    t.column "created_at", :datetime
  end

  create_table "feedbacks", :force => true do |t|
    t.column "comment",    :text,     :default => "", :null => false
    t.column "created_at", :datetime,                 :null => false
  end

  create_table "qualitative_surveys", :force => true do |t|
    t.column "course_id",       :integer,                  :null => false
    t.column "num",             :integer,                  :null => false
    t.column "answer",          :text,     :default => "", :null => false
    t.column "created_at",      :datetime,                 :null => false
    t.column "updated_at",      :datetime,                 :null => false
    t.column "user_name",       :string,   :default => "", :null => false
    t.column "hashed_password", :string,   :default => "", :null => false
    t.column "password_salt",   :string,   :default => "", :null => false
  end

  add_index "qualitative_surveys", ["course_id"], :name => "fk_qualitative_surveys_course_id"

  create_table "reviews", :force => true do |t|
    t.column "user",       :string,   :limit => 20, :default => "", :null => false
    t.column "hashed_pw",  :string,                 :default => "", :null => false
    t.column "salt",       :string,                 :default => "", :null => false
    t.column "comment",    :text,                   :default => "", :null => false
    t.column "course_id",  :integer,                                :null => false
    t.column "parent_id",  :integer
    t.column "created_at", :datetime,                               :null => false
    t.column "updated_at", :datetime,                               :null => false
  end

  add_index "reviews", ["course_id"], :name => "fk_reviews_course_id"

  create_table "sessions", :force => true do |t|
    t.column "session_id", :string
    t.column "data",       :text
    t.column "updated_at", :datetime
  end

  add_index "sessions", ["session_id"], :name => "index_sessions_on_session_id"
  add_index "sessions", ["updated_at"], :name => "index_sessions_on_updated_at"

  create_table "surveys", :force => true do |t|
    t.column "course_id",  :integer,  :null => false
    t.column "user_id",    :integer
    t.column "q1",         :integer,  :null => false
    t.column "q2",         :integer,  :null => false
    t.column "q3",         :integer,  :null => false
    t.column "q4",         :integer,  :null => false
    t.column "q5",         :integer,  :null => false
    t.column "q6",         :integer,  :null => false
    t.column "q7",         :integer,  :null => false
    t.column "q8",         :integer,  :null => false
    t.column "created_at", :datetime, :null => false
  end

  add_index "surveys", ["course_id"], :name => "fk_surveys_course_id"

  create_table "users", :force => true do |t|
    t.column "name",                :string,   :default => "", :null => false
    t.column "email",               :string,   :default => "", :null => false
    t.column "hashed_password",     :string,   :default => "", :null => false
    t.column "salt",                :string,   :default => "", :null => false
    t.column "created_at",          :datetime,                 :null => false
    t.column "updated_at",          :datetime,                 :null => false
    t.column "authorization_token", :string
  end

end
